export const data = [
  
  {
    id:1,
    university: "C University The College",
    location: "Sydney, Australia",
    rank: "8",
    career: "Accounting and finance",
    totalStudents: "3000",
    ieltsRequired: "7",
  },
  {
    id:2,
    university: "D University The College",
    location: "Sydney, Australia",
    rank: "9",
    career: "Accounting and finance",
    totalStudents: "3000",
    ieltsRequired: "7",
  },
  {
    id:3,
    university: "E University The College",
    location: "Sydney, Australia",
    rank: "5",
    career: "Accounting and finance",
    totalStudents: "3000",
    ieltsRequired: "7",
  },
  {
    id:4,
    university: "F University The College",
    location: "Sydney, Australia",
    rank: "6",
    career: "Accounting and finance",
    totalStudents: "3000",
    ieltsRequired: "7",
  },
  {
    id:5,
    university: "G University The College",
    location: "Sydney, Australia",
    rank: "7",
    career: "Accounting and finance",
    totalStudents: "3000",
    ieltsRequired: "7",
  },
  {
    id:6,
    university: "H University The College",
    location: "Sydney, Australia",
    rank: "8",
    career: "Computer Science",
    totalStudents: "3000",
    ieltsRequired: "7",
  },
  {
    id:7,
    university: "Western Sydney University The College",
    location: "Sydney, Australia",
    rank: "9",
    career: "Accounting and finance",
    totalStudents: "3000",
    ieltsRequired: "7",
  },
  {
    id:8,
    university: "I University The College",
    location: "Sydney, Australia",
    rank: "8",
    career: "Accounting and finance",
    totalStudents: "3000",
    ieltsRequired: "7",
  },
  {
    id:9,
    university: "J University The College",
    location: "Sydney, Australia",
    rank: "6",
    career: "Accounting and finance",
    totalStudents: "3000",
    ieltsRequired: "7",
  },
  {
    id:10,
    university: "Western Sydney University The College",
    location: "Sydney, Australia",
    rank: "7",
    career: "Computer Science",
    totalStudents: "3000",
    ieltsRequired: "7",
  },
  {
    id:11,
    university: "Western Sydney University The College",
    location: "Sydney, Australia",
    rank: "5",
    career: "Computer Science",
    totalStudents: "3000",
    ieltsRequired: "7",
  },
  {
    id:12,
    university: "A University The College",
    location: "Sydney, Australia",
    rank: "6",
    career: "Computer Science",
    totalStudents: "3000",
    ieltsRequired: "7",
  },
  {
    id:13,
    university: "B University The College",
    location: "Sydney, Australia",
    rank: "7",
    career: "Accounting and finance",
    totalStudents: "3000",
    ieltsRequired: "7",
  },
];
